version: '3'
services:
  wallhaven-api:
    image: fuzhume/wallhaven-api:v1.0.1
    container_name: wallhaven-api
    ports:
      - "8360:8360"
    restart: always
  wallhaven-web:
    image: fuzhume/wallhaven-web:v1.0.1
    container_name: wallhaven-web
    ports:
      - "8800:80"
    restart: always
